version: "3.8"

services:
  trino-coordinator:
    build:
      context: dockerfiles
      dockerfile: Dockerfile.trino
    container_name: trino-coordinator
    hostname: trino-coordinator
    ports:
      - "8080:8080"
      - "9080:9080"
      - "12345:12345"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 2G
    volumes:
      - "${PWD}/coordinator/config.properties:/etc/trino/config.properties"
      - "${PWD}/coordinator/jvm.config:/etc/trino/jvm.config"
      - "${PWD}/coordinator/jmx.config.yaml:/etc/trino/jmx/config.yaml"
    networks:
      trino-internal:
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/v1/status | grep '200'",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  trino-worker:
    image: trinodb/trino:433
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 2G
    volumes:
      - "${PWD}/worker/config.properties:/etc/trino/config.properties"
    networks:
      trino-internal:
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/v1/status | grep '200'",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  prometheus:
    image: prom/prometheus:v2.50.0 # fix version to avoid breaking changes in future releases
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - "${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      trino-internal:

networks:
  trino-internal:
    driver: bridge

volumes:
  prometheus-data:
