FROM trinodb/trino:433
USER root
RUN curl -L https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.20.0/jmx_prometheus_javaagent-0.20.0.jar \
  -o /usr/lib/trino/lib/jmx_prometheus_javaagent.jar
USER trino
